### ISSUE TITLE
Reformatage de `category-display.html`

### ISSUE THREAD

**Issue by tlunet** [cssb-dev/infos#3]
- [x] Utiliser des paramètres pour `category-card.html`
- [x] Trier site.pages pour afficher d'abord sous-catégories et ensuite page  
- [x] Ajouter un rank pour chaque page et afficher avec un sort sur le rank, cf [doc](https://shopify.github.io/liquid/filters/sort/)

**Comment by NANO-ck** [comment]
Utiliser des paramètres pour category-card.html => Je crains que ça soit moins propre à l'intégration du index.html d'une catégorie

**Comment by tlunet** [comment]
> Utiliser des paramètres pour category-card.html => Je crains que ça soit moins propre à l'intégration du index.html d'une catégorie

T'as un example pour illustrer ça ?

**Comment by NANO-ck** [comment]
ça change peu mais ça passe de 
{% include category-display.html %}
à
{% include category-display.html p=page %}

**Comment by tlunet** [comment]
Oui, parceque t'as ce renaming the `page` en `p` avec la boucle for. Dans l'ideal, il vaudrait mieux garder par convention la variable `page` pour indiquer la page courante (pour éviter des confusions), cad :

- virer le `{% assign p=page %}` du début, 
- `for p in site.pages` (au lieu de `for page in site.pages`) et correction des noms de variable après,
- `{% include category-display.html page=p %}`,
- dans le `category-display.html`, eventuellement faire un  `{% assign page=include.page %}` pour éviter de se taper le `include` à chaque fois.

Est-ce que t'y vois un problème que j'aurais pas réalisé ?

**Comment by NANO-ck** [comment]
Ok ça avance dans [6432090](https://github.com/cssb-dev/infos/commit/6432090dff845359aec7f18863b84da260596fa8)

**Comment by NANO-ck** [comment]
Done in 49ed911
