### ISSUE TITLE
Ajouter catégorie Chefs + première pages

### ISSUE THREAD

**Issue by remi-cssb** [cssb-dev/infos#5]
- [x] Procédures radio (pour le camp 2023)

[Ch2_Procédures_radios_et_messages.pdf](https://github.com/cssb-dev/infos/files/11243133/Ch2_Procedures_radios_et_messages.pdf)

**Comment by NANO-ck** [comment]
[transmissions - CSSB Manuel Incendie V01 2 - Référentiel incendie CSSB V01.pdf](https://github.com/cssb-dev/infos/files/11248216/transmissions.-.CSSB.Manuel.Incendie.V01.2.-.Referentiel.incendie.CSSB.V01.pdf)

**Comment by tlunet** [comment]
> [transmissions - CSSB Manuel Incendie V01 2 - Référentiel incendie CSSB V01.pdf](https://github.com/cssb-dev/infos/files/11248216/transmissions.-.CSSB.Manuel.Incendie.V01.2.-.Referentiel.incendie.CSSB.V01.pdf)

Nice ! Par contre, si tu commences mettre toutes ces infos dans la doc, probablement que ça vaut le coup de mettre une catégorie `Chefs > Transmissions Radio`, et de mettre les différentes pages dedans. Et rien n'empêches d'avoir une catégorie `Camps > Chefs` avec les informations spécifiques pour les chefs, et une page avec la tentative de procédure radio en zone que l'on essayerai de mettre en place pour le camp 2023 (avec liens pour plus de détails vers les pages de `Chefs > Transmissions Radio` ...)

**Comment by NANO-ck** [comment]
3f82ef4
Je ne suis pas certain que c'est ce qu'il fallait faire

**Comment by tlunet** [comment]
Pas tout à fait :sweat_smile: ... l'idée était plutôt de mettre en place une proposition de procédure radio avec zones pour le camps, que toutes les compagnies soient sur le même canal et de centraliser les BOT ('après ce que m'as dit Vianney, t'avais commencé à travailler dessus). Mais tkt, c'est une bonne base, et on en discutera lors de la prochaine réunion

**Comment by NANO-ck** [comment]
[Fréquence Unique - CSSB.pdf](https://github.com/cssb-dev/infos/files/11259086/Frequence.Unique.-.CSSB.pdf)
Ah oui donc ça serait plutôt basé là dessus? ça reste encore peu défini
